language: python
install:
  - pip install tox
  - pip install coverage coveralls

script:
  - tox

after_success:
  - coverage report --omit "src/registration/migrations/*.py" -m "src/registration/*.py"
  - coveralls
