language: python
python:
 - 2.6
 - 2.7
 - 3.3

env:
 - DJANGO_VERSION=1.2.7
 - DJANGO_VERSION=1.3.7
 - DJANGO_VERSION=1.4.10
 - DJANGO_VERSION=1.5.5
 - DJANGO_VERSION=1.6

install:
  - pip install -qr requirements-test.txt
  - pip install -q coverage coveralls

script:
  - coverage run --source=src/permission setup.py test

after_success:
  - coverage report --omit "src/permission/tests/compatibility.py,src/permission/conf.py" -m src/permission/*.py
  - coveralls

matrix:
    exclude:
        - python: 3.3
          env: DJANGO_VERSION=1.2.7
        - python: 3.3
          env: DJANGO_VERSION=1.3.7
        - python: 3.3
          env: DJANGO_VERSION=1.4.10

